### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by pygospa** [samuelcust/flappy-bird-assets#1]
Hi,
as you didn't include a licence file to this repo, this basically means one cannot use them for own implementation. Could you add one? 
Best regards!

**Comment by weerdy15** [comment]
Even added pull request :/ #2

**Comment by weerdy15** [comment]
He closed the pr, so, i guess there wont be an open source license at all

**Comment by prakash-niroula** [comment]
i know this is a year after but he has similar repository containing the license :- https://github.com/samuelcust/flappy-bird
It also contains assets similar to this so it should be MIT licensed

**Comment by samuelcust** [comment]
Added the LICENSE file in the [v.1.1.0](https://github.com/samuelcust/flappy-bird-assets/releases/tag/v1.1.0)

**Comment by elenakrittik** [comment]
Finally, thanks!
