### ISSUE TITLE
cant download the sprites

### ISSUE THREAD

**Issue by SarthakSingh07** [samuelcust/flappy-bird-assets#3]
i am not able to download the assests

**Comment by quick007** [comment]
![image](https://user-images.githubusercontent.com/69743171/181937443-b2d2dcba-750f-447e-b3da-33b571c06f15.png)

**Comment by samuelcust** [comment]
You can now download a release: [v1.0.0](https://github.com/samuelcust/flappy-bird-assets/releases/tag/v1.0.0)
